### ISSUE TITLE
Install fails with MissingTargetFrameworkException

### ISSUE THREAD

**Issue by TaoK** [tom-englert/Wax#10]
Attempted to install V 1.0.17.0 "wax.vsix" package (from gallery or standalone) in VS2013 Community on Windows 10, and get:

Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'Wax' requires a version of the .NET Framework that is not installed.

This appears to be a problem with framework 4.6 detection in some other extensions (eg https://github.com/dungpa/PowerTools/commit/e352ec5ea1a46b1007b2923fe888bdbeb421ded4), I assume the same applies here.

**Comment by tom-englert** [comment]
@TaoK: did this fix your problem?
