### ISSUE TITLE
DirectoryRef Id attribute is not a legal identifier

### ISSUE THREAD

**Issue by Tim-The-Woodsman** [tom-englert/Wax#11]
Hi! 

I'm creating a setup project with WiX Toolset and Wax and I'm running into an issue (multiple to be honest) with fragments containing directory info

```
  <Fragment>
    <DirectoryRef Id="TODO:b6cbd831-7eeb-4f74-92a2-398332a91b43">
      <Directory Id="assets_bootstrap_3.3.5_css" Name="css" />
    </DirectoryRef>
  </Fragment>
```

I have no clue where the "TODO:" comes from or what to do about it. 

I tried to replace those illegal characters with underscores, creating the Id "TODO_b6cbd831_7eeb_4f74_92a2_398332a91b43", but now I'm seing the error 

```
Unresolved reference to symbol 'Directory:TODO_b6cbd831_7eeb_4f74_92a2_398332a91b43' in section 'Fragment:'
```

I'm relatively new to WiX and I'm not quite sure how to reference the symbol as I'm not seing the Guid "b6cbd831-7eeb-4f74-92a2-398332a91b43" anywhere in my project.

Thanks in advance for any help!

**Comment by tom-englert** [comment]
This can happen if Wax can't deduce the parent folder from the project. In this case it's up to you to specify the correct parent, that's what the TODO: means - replace the whole name with the name of the valid parent directory node.

How does your project structure look like? Can you provide a sample?

**Comment by Tim-The-Woodsman** [comment]
I'm sorry for the paranoid mockup but my client is ... special :-)

![2016-11-29 18-08-48](https://cloud.githubusercontent.com/assets/13421484/20720321/fcaef61a-b65e-11e6-86b8-118bf0f07c06.png)

It's a relatively complex structure and I'm not the one who created it. I just didn't touch it after the original installer is made of pure pain and a plain text configuration file. Could it be the complexity of the project?

Thank you for your quick reply!

**Comment by tom-englert** [comment]
I found the problem, it's the deep nesting of folders, where only the last folder contains files.

So your directory tree should look something like this:
```
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="INSTALLDIR" Name="WPF_Project">
        <Directory Id="assets" Name="assets">
          <Directory Id="assets_bootstrap" Name="bootstrap">
            <Directory Id="assets_bootstrap_3.3.5" Name="3.3.5">
              <Directory Id="assets_bootstrap_3.3.5_css" Name="css"/>
...
```

I will fix this in Wax and make a new release ASAP.

**Comment by Tim-The-Woodsman** [comment]
Thank you very much! 

I think I'll use this opportunity to ditch the deep nesting. It only occured because the last dev downloaded some pages from a web site and hosted it in an self hosted server without changing anything. 

Thank you again! You did a great job!

**Comment by Tim-The-Woodsman** [comment]
Fixing my directories solved the issue. Thank you for your help!
