### ISSUE TITLE
Error Installing Extension

### ISSUE THREAD

**Issue by RoarkDude** [tom-englert/Wax#14]
Getting an unable to find file error installing for VS 2017 RC.  Here's the install log:

1/2/2017 8:27:32 PM - Microsoft VSIX Installer
1/2/2017 8:27:32 PM - -------------------------------------------
1/2/2017 8:27:32 PM - vsixinstaller.exe version:
1/2/2017 8:27:32 PM - 15.0.26014.0 built by: D15REL
1/2/2017 8:27:32 PM - -------------------------------------------
1/2/2017 8:27:32 PM - Command line parameters:
1/2/2017 8:27:32 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:15.0.26014.0,/appidname:Microsoft Visual Studio Community 2017 RC,C:\Users\Peter\AppData\Local\Temp\VSIXbzd2o1o0.vsix
1/2/2017 8:27:32 PM - -------------------------------------------
1/2/2017 8:27:32 PM - Microsoft VSIX Installer
1/2/2017 8:27:32 PM - -------------------------------------------
1/2/2017 8:27:32 PM - Initializing Install...
1/2/2017 8:27:32 PM - Extension Details...
1/2/2017 8:27:32 PM - 	Identifier         : 6b9b0621-c739-4ee5-9834-a0ba2a8d3596
1/2/2017 8:27:32 PM - 	Name               : Wax
1/2/2017 8:27:32 PM - 	Author             : tom-englert.de
1/2/2017 8:27:32 PM - 	Version            : 1.0.19.0
1/2/2017 8:27:32 PM - 	Description        : An interactive WiX-Setup editor; easily maintain the files to be installed.
1/2/2017 8:27:32 PM - 	Locale             : en-US
1/2/2017 8:27:32 PM - 	MoreInfoURL        : https://github.com/tom-englert/Wax
1/2/2017 8:27:32 PM - 	InstalledByMSI     : False
1/2/2017 8:27:32 PM - 	SupportedFrameworkVersionRange : [4.5,)
1/2/2017 8:27:32 PM - 
1/2/2017 8:27:32 PM - 	SignatureState     : Unsigned
1/2/2017 8:27:32 PM - 	Supported Products : 
1/2/2017 8:27:32 PM - 		Microsoft.VisualStudio.Pro
1/2/2017 8:27:32 PM - 			Version : [11.0,16.0)
1/2/2017 8:27:32 PM - 		Microsoft.VisualStudio.Community
1/2/2017 8:27:32 PM - 			Version : [11.0,16.0)
1/2/2017 8:27:32 PM - 		Microsoft.VisualStudio.Enterprise
1/2/2017 8:27:32 PM - 			Version : [11.0,16.0)
1/2/2017 8:27:32 PM - 
1/2/2017 8:27:32 PM - 	References         : 
1/2/2017 8:27:32 PM - 		-------------------------------------------------------
1/2/2017 8:27:32 PM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
1/2/2017 8:27:32 PM - 		Name         : Visual Studio MPF 11.0
1/2/2017 8:27:32 PM - 		Version      : [11.0,12.0)
1/2/2017 8:27:32 PM - 		MoreInfoURL  : 
1/2/2017 8:27:32 PM - 		Nested       : No
1/2/2017 8:27:32 PM - 
1/2/2017 8:27:32 PM - 	Prerequisites      : 
1/2/2017 8:27:32 PM - 		-------------------------------------------------------
1/2/2017 8:27:32 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/2/2017 8:27:32 PM - 		Name         : Visual Studio core editor
1/2/2017 8:27:32 PM - 		Version      : [15.0.25824.0,16.0)
1/2/2017 8:27:32 PM - 
1/2/2017 8:27:32 PM - Signature Details...
1/2/2017 8:27:32 PM - 	Extension is not signed.
1/2/2017 8:27:32 PM - 
1/2/2017 8:27:35 PM - The extension with ID '6b9b0621-c739-4ee5-9834-a0ba2a8d3596' is not installed to Microsoft Visual Studio Community 2017 RC.
1/2/2017 8:27:46 PM - The following target products have been selected...
1/2/2017 8:27:46 PM - 	Microsoft Visual Studio Community 2017 RC
1/2/2017 8:27:46 PM - 
1/2/2017 8:27:48 PM - Beginning to install extension to Microsoft Visual Studio Community 2017 RC...
1/2/2017 8:27:48 PM - Install Error : System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by tom-englert** [comment]
Can you install other extensions?

**Comment by RoarkDude** [comment]
Yes, in fact this extension installed for VS 2013 Ultimate and VS 2015 Pro.

**Comment by tom-englert** [comment]
Feedback from Microsoft: (summarized)

Based on the callstack, the file not found is likely the native setup API dll missing on the machine but without any repro steps it’s unclear how the customer may have gotten into this situation. 
...
I think this could actually be caused by a corrupted install on Willow.  Currently the VSIXInstaller only enumerates successful Willow installs, so if for any reason an install on Willow is unsuccessful (modify, remove or upgrade), installing extensions afterwards can run into this issue.  There’s a bug on my plate to enumerate all Willow install instances (not just the successful ones), so that should hopefully address things
