### ISSUE TITLE
Handling second-tier references

### ISSUE THREAD

**Issue by Leogiciel** [tom-englert/Wax#15]
I use [this nuget package](https://www.nuget.org/packages/ServerAppFabric.Client/1.0.2912) which delivers four dlls but references only the top two of them in the csproj. (see [my post on SO](http://stackoverflow.com/a/41440719/1723397) explaining this behaviour).

VS and MSbuild both do right at compilation, detecting references from other two libraries and resolving them because they are on the same folder (according to [this post](http://www.beefycode.com/post/resolving-binary-references-in-msbuild.aspx) ) and the four libraries are in the bin folder. 

Wax doesn't detect them, and I understand that's because it's based on csproj file, but if MSBuild can do it maybe we can too ?

Regards

**Comment by Leogiciel** [comment]
I'm working on it, and I'll send you a pull request.

**Comment by tom-englert** [comment]
Using Assembly.LoadFile is dangerous, the file will be locked by the VS process forever. I have refactored it using Mono.Cecil  (https://github.com/tom-englert/Wax/commit/d36a782b7ffb5d25f897262b4458c14779e02e14)

**Comment by Leogiciel** [comment]
Nice ! Thank you for the tip, I didn't know about Cecil, it looks amazing !
