### ISSUE TITLE
Unreadable labels when VS is in dark mode

### ISSUE THREAD

**Issue by Leogiciel** [tom-englert/Wax#17]
![screenshot_4](https://cloud.githubusercontent.com/assets/1555868/21636089/7b92927a-d261-11e6-82dd-36160bf7a9f8.png)

**Comment by Leogiciel** [comment]
I'm working on it, I'll send you a pull request

**Comment by Leogiciel** [comment]
I'll try to fix this

**Comment by tom-englert** [comment]
I already have the styles for the themes ready (see e.g. https://github.com/tom-englert/ResXResourceManager), I just had no time yet to implement them here.

**Comment by Leogiciel** [comment]
I saw your TODO in the code ;)
