### ISSUE TITLE
The directory name: x64 is the same as one of the MSI Public Properties and can cause unforeseen side effects

### ISSUE THREAD

**Issue by maikebing** [tom-englert/Wax#19]
> error LGHT0204: ICE99: The directory name: x64 is the same as one of the MSI Public Properties and can cause unforeseen side effects. [D:\Multi-Runner\builds\3c61e4ea\0\maikebing\DES\src\DES.Installer\DES.Installer.wixproj]

Wrong code：
<Directory Id="x64" Name="x64" />`

Resolvent:
[http://stackoverflow.com/questions/16851193/with-wix-distribute-a-program-that-uses-sqlite-must-work-on-both-32bit-and-64b](http://stackoverflow.com/questions/16851193/with-wix-distribute-a-program-that-uses-sqlite-must-work-on-both-32bit-and-64b
)

My code
`    <Directory Id="DIR_x64" Name="x64" />`

Can you fix this problem in the new version？

**Comment by tom-englert** [comment]
This is not an issue of Wax - it just helps you to maintain the file list in .wxs files - it does not compile your code.

Your issue is using illegal ids, and the stackoverflow article already has the answer.

**Comment by maikebing** [comment]
This is the wax generated by ID, because SQLite relies on X86 and x64 files. Using the wax will automatically generate the ID.
Can WAX avoid generating such ID?

**Comment by Leogiciel** [comment]
@maikebing : You can force wax to prefix directory ids by "dir_". To do that, just replace the line 44 of the WixDirectoryNode.cs file : 
`var directoryElement = new XElement(WixNames.DirectoryNode, new XAttribute("Id", id), new XAttribute("Name", name));`
by : 
`var directoryElement = new XElement(WixNames.DirectoryNode, new XAttribute("Id", "dir_" + id), new XAttribute("Name", name));`

@tom-englert : Maybe you can implement this, it will avoid some other conflicts like this one ?

**Comment by Leogiciel** [comment]
@maikebing : To achieve this, you can replace line 154 of file WaxProject.cs : 
`return (_configuration.DirectoryMappings.TryGetValue(directory, out value) && (value != null)) ? value : GetDefaultId(directory);`

by : 
`return (_configuration.DirectoryMappings.TryGetValue(directory, out value) && (value != null)) ? value : string.Concat("dir_",GetDefaultId(directory));`

**Comment by maikebing** [comment]
OK！

**Comment by tom-englert** [comment]
The solution suggested by @Leogiciel would break backward compatibility, so I have added a more specific workaround.
However you can always create your own id's an just add a custom mapping in Wax.

@maikebing: I am also using SQLite in some projects, but SQLite has a post-build step to copy those files, and I had to maintain those entries manually, so I wonder how Wax can know about these directories?
