### ISSUE TITLE
ASP.Net non-standard output

### ISSUE THREAD

**Issue by Leogiciel** [tom-englert/Wax#21]
In ASP.Net applications, MSBUILD generates all dlls and pdbs in TargetDir, but project.FileName is like "{TargetDir}\bin\mainAssembly.dll" for main assembly dll and pdb.

@tom-englert fixed the source file location, removing the hard-coded "bin", but this folder is here to indicate to VS how to deploy the web application : when publishing the web application puts effectively every dll and pdb files into a bin subfolder (eg : {TargetDir}\bin\everydlls.dll).

I'll implement a "non standard output" detection when removing "bin" from the source path, to add it automatically when generating FileComponents in wix file.

**Comment by tom-englert** [comment]
That is already fixed for #13: https://github.com/tom-englert/Wax/commit/b49c60a4f82aeaaad4ba74393194e709df337b6f - or is there another issue I did not see?

It was not really "non standard output", but wrong interpretation of these file names - it's the target dir, and all references just have to follow this, while the source is just the file name without folder.

**Comment by Leogiciel** [comment]
It is another issue. Winmerge Wax MSI's output folder and build output folder and it's OK. That's your fix and it helped me ! Then right-click your project and chose "Publish..." (the right way to deploy an ASP site or API) and WinMerge your taget folder and your Wax MSI's output folder : every dlls (and pdbs) are published (deployed) in the hardcoded bin folder under the target dir...I'm already done with the fact, pull request is arriving tomorrowRegardsBrice Andreota Le 5 janv. 2017 7:41 PM, tom-englert <notifications@github.com> a écrit :That is already fixed for #13: b49c60a - or is there another issue I did not see?
It was not really "non standard output", but wrong interpretation of these file names - it's the target dir, and all references just have to follow this, while the source is just the file name without folder.

**Comment by Leogiciel** [comment]
I didn't see your last commit [b49c60a](https://github.com/tom-englert/Wax/commit/b49c60a4f82aeaaad4ba74393194e709df337b6f) yesterday, sorry about that.

I tried your fix, but second-tier references are not going into bin but only in targetdir.

My implementation in my last pull request differs from yours, but is working as expected.

You can choose to implement it the way you want :)

Regards

**Comment by Leogiciel** [comment]
Fixed with commit [0d1a824](https://github.com/tom-englert/Wax/commit/0d1a824c16a709f4205d5048b2f84420b05aba36)
