### ISSUE TITLE
Duplicated references since second-tier references are detected

### ISSUE THREAD

**Issue by Leogiciel** [tom-englert/Wax#26]
Adding a GroupBy in GetProjectOutput handles the case when many versions of second-tier references are detected and duplicated in wxs file.

**Comment by tom-englert** [comment]
I don't experience this behavior, maybe that's only in your code?

**Comment by Leogiciel** [comment]
It happens only if two references reference the same second-tier reference in different nuget packages versions. Not easy to reproduce, try to reference a project which reference an older version of a nuget you reference in the main project

**Comment by Leogiciel** [comment]
Fixed with commit [0d1a824](https://github.com/tom-englert/Wax/commit/0d1a824c16a709f4205d5048b2f84420b05aba36)
