### ISSUE TITLE
DMSDB.Context.tt is not need !but !!!

### ISSUE THREAD

**Issue by maikebing** [tom-englert/Wax#28]
![tt](https://cloud.githubusercontent.com/assets/3445167/21811777/daef400e-d78b-11e6-83de-c231a7b0463a.PNG)
![tt2](https://cloud.githubusercontent.com/assets/3445167/21811790/e0f29ee2-d78b-11e6-81a8-bdb34f8510b5.PNG)

**Comment by Leogiciel** [comment]
You have to set its Property from "Build action : Content" to "Build action : None". 

Wax is based on the csproj file, so files which are in "Build action : Content" would be detected, and that's a standard behaviour.

**Comment by maikebing** [comment]
Thank you very much for your patience!
But the output is not "copied to the output directory" , so I think it should not be brought in wix！

**Comment by tom-englert** [comment]
Can you send me the project file, so I can check what goes wrong here?

**Comment by maikebing** [comment]
[WindowsFormsApplication5.pdf](https://github.com/tom-englert/Wax/files/707384/WindowsFormsApplication5.pdf)


i can't upload zip files , so  download this file , rename plase!
this project file for #29  #28

**Comment by maikebing** [comment]
\zh-Hans\EntityFramework.resources.dll" not include by  wax , you can test for #29

**Comment by tom-englert** [comment]
Build action of the .tt files is "Content" - and all content will be reported by VS as project output, no matter if copy to output directory is checked or not. 

You must change the build action to none.
