### ISSUE TITLE
Vertical Scrollbar

### ISSUE THREAD

**Issue by simont1611** [tom-englert/Wax#3]
Just the tool I am looking for, however no vertical scrollbar makes it unusable for large projects.  Am I missing something?

**Comment by tom-englert** [comment]
Where are you missing a scroll bar? 
There has been a scrolling issue once, but this was fixed in Jan. 2015 with V 1.05

**Comment by simont1611** [comment]
I have included a screen print to illustrate.
I am running the latest build from nuget which is 1.0.13.0

![image](https://cloud.githubusercontent.com/assets/12081235/16646500/52bf8e3e-4422-11e6-8cf0-3945bee99452.png)

**Comment by tom-englert** [comment]
I see, its a large number of folders, not just files.
