### ISSUE TITLE
VS 2015 Update 3 Crash

### ISSUE THREAD

**Issue by vbjay** [tom-englert/Wax#4]
Make sure visual studio 2015 is up to date.  Clone [gitextensions](https://github.com/gitextensions/gitextensions) and run the vs 2015 build cmd file to make sure all nuget packages are pulled down.  Open 2015 sln and try to show the WAX tool.

WIX Toolset:
![image](https://cloud.githubusercontent.com/assets/3629489/16643256/dbee79aa-43e0-11e6-9ed9-298068be9c9b.png)

**Comment by tom-englert** [comment]
Works fine here - do you have a stack trace?

**Comment by vbjay** [comment]
Uninstalled and reinstalled.  It is fine now.
