### ISSUE TITLE
MSBuild

### ISSUE THREAD

**Issue by watsug** [tom-englert/Wax#40]
Is it possible to integrate this tool with MSBuild only? We do not have VS installed on build server (Jenkins). So the question is what can we do?

**Comment by tom-englert** [comment]
Wax is just an interactive editor to maintain your wix source files.
What you need to install on the build server is the WiX Toolset (http://wixtoolset.org/)

**Comment by maikebing** [comment]
@watsug  
use 
  ` %comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsMSBuildCmd.bat""`

and 

`msbuild.exe   %1   /t:Rebuild   /p:Configuration=Release;Platform="x86"`

you can add task to  Jenkins !

**Comment by maikebing** [comment]
@watsug    WiX  will WiX project will be compiled ！
Wax just a editor !
