### ISSUE TITLE
Root Directory Values In Dropdown Missing

### ISSUE THREAD

**Issue by Zabalba** [tom-englert/Wax#41]
Hello Tom,

I'm trying to get started creating deployment packages using WiX and your tool Wax. After installing Wix and installing the Wax extension, I create a new WixToolset Setup Project. Once the project is added, I went to Tools -> Wix Setup Editor. In there, dialog box 2 does not display anything to select on. Did I miss a step? I'm using Visual Studio 2015 Community and the Wix project was under the framework 3.5.2.

**Comment by tsahi** [comment]
I have WiX Toolset 3.10 and Wix Toolset Visual Studio 2015 Extension 0.9.17.13693 installed (not sure what's the latter for). When I add a new project, contrary to your readme.md, the WiX project template is at Wix Toolset, where there are two sub-types: v3 and v4.

When I select Setup Project from v4, I encounter the issue described above. But when I select Setup Project from v3, I can see a root directory in the drop down.

**Comment by tom-englert** [comment]
I never used the v4 templates, since they seem to be designed to work with WiX Tooset 4.x, which has no releases yet - so you have to use the v3 templates anyhow.

Whenever 4.x gets released, I will try to make it work with the new version, too.

**Comment by tsahi** [comment]
It's still worth updating your documentation about the location of the template item.
