### ISSUE TITLE
Support for deploying Office VSTO Add-In

### ISSUE THREAD

**Issue by saf-itpro** [tom-englert/Wax#43]
Does it support the above? I'm interested in using it to deploy an MS WORD [VSTO Add-In](https://msdn.microsoft.com/en-us/library/cc442946.aspx). Thanks..Saf

**Comment by tom-englert** [comment]
According to https://msdn.microsoft.com/en-us/library/bb386179.aspx windows installer is OK.

Wax will help you maintaining the files to be installed; for all other questions see http://wixtoolset.org/
