### ISSUE TITLE
Open an existing Wix project with Wax?

### ISSUE THREAD

**Issue by ksmiller99** [tom-englert/Wax#46]
Is it possible to open and existing Wix project with Wax? I inherited a large Wix project that now requires changes. There are multiple developers in the repo and I'd rather not make a new project.

**Comment by tom-englert** [comment]
Of course, since it only edits existing projects - you even can't create new projects with Wax. 
If the project already contains directory and file entries, you just have to setup/confirm the existing mappings and eventually solve ambiguities once.
