### ISSUE TITLE
Adding Altova UModel takes out wax

### ISSUE THREAD

**Issue by XanthiusChristenson** [tom-englert/Wax#48]
I added Altova UModel to a project after Wax was already installed and it throws a bunch of errors now.
![error](https://user-images.githubusercontent.com/30056938/30067582-69e03858-9218-11e7-9f02-5ed63a44c183.GIF)

**Comment by XanthiusChristenson** [comment]
If you know why please help

**Comment by tom-englert** [comment]
Please try the latest build from http://vsixgallery.com/

**Comment by XanthiusChristenson** [comment]
It still didn't work.

**Comment by tom-englert** [comment]
Same exception?

**Comment by XanthiusChristenson** [comment]
Not quite 
![error2](https://user-images.githubusercontent.com/30056938/30113749-f507440c-92d2-11e7-9872-54a2e0ba03e2.GIF)

**Comment by tom-englert** [comment]
Did this "UModel" add a new project to your solution?

**Comment by XanthiusChristenson** [comment]
It was already involved with this project is has lots of added material I only added the visual studio extension part for UModel to give me use of the UModeling that I've done. That was when I noticed that Wax was throwing exceptions.

**Comment by tom-englert** [comment]
There is a project in your solution that seems to be only partially implemented - what kind's of projects are in your solution? Only C#/VB?

**Comment by XanthiusChristenson** [comment]
UModel writes C#

**Comment by tom-englert** [comment]
but there must be at least one project in your solution that is not C# - Visual Studio projects don't have those properties not implemented.

**Comment by XanthiusChristenson** [comment]
I think from what i am gathering from UModel is that the diagrams might be UML other than that this program has .ico and .dll and .inf included but that is it.

**Comment by tom-englert** [comment]
Are the diagrams in a separate project of your solution?

**Comment by XanthiusChristenson** [comment]
No they are under the Umodel file tree project.

**Comment by tom-englert** [comment]
I added another check, try the try the latest build from http://vsixgallery.com/

**Comment by tom-englert** [comment]
What is the "Umodel file tree project"?

**Comment by XanthiusChristenson** [comment]
That fixed it Thanks!  Much appreciated

**Comment by tom-englert** [comment]
I would still like to understand what the "Umodel file tree project" is.

**Comment by XanthiusChristenson** [comment]
Ya that was a pour choice of words. But it is the solution explorer Project file sub files( File Tree).

**Comment by tom-englert** [comment]
You have a screen shot?

**Comment by XanthiusChristenson** [comment]
Here Like i said poor choice of words. 
![screenshot](https://user-images.githubusercontent.com/30056938/30116163-1584624e-92da-11e7-8cdf-8378643004e2.GIF)

**Comment by tom-englert** [comment]
I see, so the *UModel.ump is a project in your solution, right?

**Comment by XanthiusChristenson** [comment]
Yes Sir. I use it for state machines diagraming

**Comment by tom-englert** [comment]
Then I understand what has happened, this is a special project kind that does no implement some basic properties.

**Comment by XanthiusChristenson** [comment]
Great I'm glad to help.
Again thanks  a lot. Wax makes Wix a lot easier to use.

**Comment by tom-englert** [comment]
You could help making it more popular by sharing your experience here: https://marketplace.visualstudio.com/items?itemName=TomEnglert.Wax#review-details 😄
