### ISSUE TITLE
[Feature Request] Add support for adding Windows Services

### ISSUE THREAD

**Issue by HeinanCA** [tom-englert/Wax#5]
Hey,
Well, as the title explains, I would love Wax to have support for adding Windows Services into the compilation.

Is that possible?

**Comment by tom-englert** [comment]
The intention of this tool is to maintain the file list, which is usually hundreds of lines and not easily to do manually.
Like #1 I don't see a real demand to introduce a complex UI to simply add two lines of XML.
The major benefit of WiX is that configuring such simple things does **not** need a UI and can be easily added in XML directly.

However if someone would like to contribute such a features, I can add it.

**Comment by HeinanCA** [comment]
My scope of looking at is it will allow adding parameters to the service. I will go over the code and try to program this functionality, and then hopefully merge it into your solution.

**Comment by tom-englert** [comment]
Closed, since there is no feedback for two years.
