### ISSUE TITLE
How to exclude a project that is detected as a dependency?

### ISSUE THREAD

**Issue by thx1200** [tom-englert/Wax#50]
My main project output has a reference to another project (EXE) that is used solely for versioning maintenance in the build process.  It is not something the user sees.  It's attached as a build event only and it's being detected as a dependency.  How do I exclude that from Wax?

**Comment by tom-englert** [comment]
Setting "Copy local" to false in the references property sheet should do the job.

**Comment by thx1200** [comment]
Oh sorry, I wasn't clear.  It's not set as a reference in the project.  That was a bad choice of words.  The "reference" I meant was that it is included as a build event action.  There is no reference to the utility project at all as far as assembly references are concerned.

**Comment by tom-englert** [comment]
Wax is only looking for project references, so I can't see why this should happen.
Can you post a sample?

**Comment by thx1200** [comment]
Ah I found it, it was set as a reference on a dependent DLL.  I was barking up the wrong tree initially.  Thanks for the help!

**Comment by tom-englert** [comment]
:smile:
