### ISSUE TITLE
Wax does not seem to pick up PackageReference dependencies

### ISSUE THREAD

**Issue by lostmsu** [tom-englert/Wax#53]
Steps:
create a new WPF project A with Visual Studio 2017 15.5
install Newtonsoft.Json into A (ensure it uses PackageReference)
create Wix Setup project B and reference A
open Wax editor for B

Expected: Newtonsoft.Json should be listed
Actual: it is not; only A.exe and A.exe.config are

**Comment by tom-englert** [comment]
How do you create a WPF project that uses `PackageRefrerence`?

**Comment by lostmsu** [comment]
My bad. I thought it is default in 15.5
There's a setting in Visual Studio settings. You can search for it inside the settings window.
