### ISSUE TITLE
Checking product in WAX editor complains references already exist

### ISSUE THREAD

**Issue by timedroid** [tom-englert/Wax#54]
Every time I attempt to check a new project under Projects to install, a "Microsoft Visual Studio" error dialog is opened for each component that has already been checked:
"A reference to component 'X' cannot be added. A reference to the component already exists in the project."

It appears all checked projects remain select and WAX attempts to add them again every time I try to check a new project.

Project Type: Setup Project for WiX v3
Visual Studio 2015 Update 3, 
Wix Toolset Visual Studio 2015 Extension 0.9.21.62588
Wax 1.1.895

**Comment by tom-englert** [comment]
@timedroid I could not reproduce this. I once had this behavior, but it was fixed long time ago.
Any more info how to reproduce this?

**Comment by tom-englert** [comment]
Closed, since no feedback received.
