### ISSUE TITLE
Wax display duplicate file to add

### ISSUE THREAD

**Issue by bernd70** [tom-englert/Wax#56]
Hi,

when reloading my wax project a file is offered twice (Red line with Unmapped state) for addition to the WiX project. It appears to some dependency resolving sind it is a DLL of a Nuget pacxkage but I found no reason why this happens so I was wondering how the list is composed. Are there any detailed log files?

Thanks
Bernd

**Comment by tom-englert** [comment]
@bernd70 it just collects all references and then does ad distinct, so there shouldn't be duplicates. I never observed this. Can you post a sample project?

**Comment by bernd70** [comment]
Tom,

thanks for getting back to me. I tried to reproduce this with a new project but wasn't able to. So I removed all the 3rdParty Nugets (Syncfusion.*) I suspected to be the culprit and added them again. This solved the problem. :-)

Bernd
