### ISSUE TITLE
Use outside of VisualStudio

### ISSUE THREAD

**Issue by amccool** [tom-englert/Wax#58]
anyway that it would be possible to use this outside of visual studio?

**Comment by tom-englert** [comment]
not so easy, who would then provide the information about the projects, their dependencies and their references?

**Comment by Leogiciel** [comment]
@amccool, Wax is clearly not designed for this use-case. You can use paraffin, which is based on the filesystem, but Wax is based on the csproj informations and not on the file system. It's the VS SDK which provides us informations.
