### ISSUE TITLE
Directory mappings only contain native lib directories

### ISSUE THREAD

**Issue by FrederickBrier** [tom-englert/Wax#60]
I am trying to write a Wix installer for a single project WPF app. The problem appears to be the inclusion of LibGit2Sharp, which pulls in LibGit2Sharp.NativeBinaries. Wax seems to be confused by the presence of the .\lib directories under .\bin\debug.

This can easily be reproduced. Create an empty .Net Framework WPF application. Build it. Add a Wix v3 setup project. Open up the Wix Setup Editor. All looks normal. Add the LibGit2Sharp NuGet package to the WPF project's references. Build it. Go back to the Wix Setup Editor and refresh. The (4) Directory mappings Directory column becomes red and is filled only with the .\lib directories. The (5) File mappings table is all red, contains all the files in the .\lib directories which are labeled Unmapped, does not scroll, and nothing can be selected.

**Comment by tom-englert** [comment]
You must first fix (4) by adding the directory before you can add files (5)

**Comment by FrederickBrier** [comment]
I am new to Wix, and could not figure out how to add the (4) Directory mappings. I have tried adding new elements to the <DirectoryMappings> element. Unfortunately, there do not seem to be any [examples on the web](https://www.google.com/search?safe=active&rlz=1C1CHZL_enUS760US760&ei=EL_ZXKzGFp2-0PEPgtuaiAQ&q=Wax+%22DirectoryMappings%22+item+key+value&oq=Wax+%22DirectoryMappings%22+item+key+value&gs_l=psy-ab.3...56262.57670..57990...0.0..0.345.973.3-3......0....1..gws-wiz.......0i71.zAd_QITN4pw) [6 results] that have more than the single element without a key.
```
  <DirectoryMappings>
    <Item Key="" Value="INSTALLFOLDER" />
  </DirectoryMappings>
```
My attempts using hardcoded values, or using Wix variables such as $(var.MyWpfProject.ProjectDir) do not add the directory as you are suggesting.
```
  <DirectoryMappings>
    <Item Key="" Value="INSTALLFOLDER" />
    <Item Key="debug" Value="d:\Projects\MyWpfProject\MyWpfProject\bin\debug" />
  </DirectoryMappings>
```
Could you please provide a more explicit example of how to add another directory, or perhaps a link on How to add the directory? Thank you.

**Comment by tom-englert** [comment]
Just click the + symbol

**Comment by tom-englert** [comment]
Just click the + symbol

**Comment by tom-englert** [comment]
And don't touch the .wax file
