### ISSUE TITLE
Implementation of conditional builds

### ISSUE THREAD

**Issue by gitkrasty** [tom-englert/Wax#62]
Dear Tom, 

When the wxs file uses conditional builds, some times the Wax tool fails with some strange exception. I could drill it down to the following small example snippets in the attached file. [Samples.txt](https://github.com/tom-englert/Wax/files/3505276/Samples.txt)

I am not sure if I do it the right way, but it does what I want to achieve and Wix can correctly process booth versions.

Wax goes this way:
![Annotation 2019-08-15 124750](https://user-images.githubusercontent.com/52275670/63090525-d94ad500-bf5b-11e9-9203-81485253f9a9.png)

**Comment by tom-englert** [comment]
I could not think of a different way to solve this
