### ISSUE TITLE
Undefined preprocessor variable '$(var.LedControl.TargetDir)'

### ISSUE THREAD

**Issue by anders-eriksson** [tom-englert/Wax#63]
Hello,
I have just installed Wix 3.11.1 and Wix Toolset Visual Studio 2017 Extension and Wax 1.4.1788 from Visual Studio Marketplace.

I have then follow your instructions but the build fails with and error
_Undefined preprocessor variable '$(var.LedControl.TargetDir)'_

It seems like the File Mappings are a bit strange (or probably I'm doing something wrong)
After clicking on + for each file I get a number of defines in Project.wxs
This is what it looks like in Wix Setup Editor
![FileMappings](https://user-images.githubusercontent.com/17025701/64069759-d71d9180-cc50-11e9-85c1-0bad6a43a37f.PNG)

This is whats added to the Project.wxs
![Product_wxs](https://user-images.githubusercontent.com/17025701/64069755-c40ac180-cc50-11e9-99bc-4b30e24f55a4.PNG)

As you can hopefully see there are some variables used that isn't defined.
LedControl
Contracts
Data
LighterWrapper
Configuration
DCLog
Profile

These are all referenced projects!

How would I fix this?

**Comment by tom-englert** [comment]
See https://wixtoolset.org/documentation/manual/v3/votive/votive_project_references.html
Usually Wax should have added project references for all these projects. This seem to have failed in your case, so just add them manually.

**Comment by DarwinOL** [comment]
I saw this same issue with the newest release. I had to revert to an older version to get things to work properly.
