### ISSUE TITLE
Error when creating WAX file

### ISSUE THREAD

**Issue by ferranmeseur** [tom-englert/Wax#65]
I get this error when opening the tool:

![image](https://user-images.githubusercontent.com/24566888/88061096-5bc61680-cb67-11ea-88a4-4ee0c9089953.png)

**Comment by tom-englert** [comment]
Looks like one of your wix files is corrupt...

**Comment by ferranmeseur** [comment]
Any fixes? I reinstalled WIX

**Comment by tom-englert** [comment]
Your project files (.wxs/.wxi) - it's an XML error.

**Comment by tom-englert** [comment]
closed as stale
