### ISSUE TITLE
Error in install WAX

### ISSUE THREAD

**Issue by leoxoxo** [tom-englert/Wax#66]
Can't install extensions because of "prerequisites that cannot be resolved"
VS2017

**Comment by tom-englert** [comment]
Which prerequisites?

**Comment by tom-englert** [comment]
@leoxoxo which prerequisites is it complaining about?

**Comment by jsalamy** [comment]
This is the message I get.  Do you know of a location i can find a log?  I have Wixtoolset 3.6, 3.11, and 4.0.  Is there something else that i am missing?  Thanks in advance.
Joe
![0001- 14-53-07-Nov-02-20](https://user-images.githubusercontent.com/20744066/97913025-b7ce3880-1d1b-11eb-95bf-66db94dfdf15.png)

**Comment by tom-englert** [comment]
There is only one prerequisite in the vsix manifest:
``` xml
    <Prerequisites>
        <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.8.27729.1,17.0)" DisplayName="Visual Studio core editor" />
    </Prerequisites>
 ```
Maybe your VisualStudio is outdated?

**Comment by jsalamy** [comment]
@tom-englert Thank you for the suggestion to update VisualStudio.  That did the trick.
