### ISSUE TITLE
Wax file Deployed Projects list is not updated when a project is referenced by another project in the list

### ISSUE THREAD

**Issue by DarwinOL** [tom-englert/Wax#73]
in version 1.6 when a project is referenced by another project the state of the checkbox changes to the intermediate state. This project is then not added to the Deployed Projects list of the wax file. In previous versions there was no intermediate state and all projects were added to the list.

**Comment by tom-englert** [comment]
The "intermediate" projects are not needed in the projects list, because they are already implicitly selected as referenced by another selected project.

They were not needed in the older versions either, there they were just displayed in a dim color

**Comment by DarwinOL** [comment]
Without the projects in the file I cannot build my installation. 
Example: Project1 is referenced by Project2.
Only Project2 shows up in the wax file. 
I need the Project1 name in there so that I can change the connection string during the installation since Project1 can also be launched stand alone.

**Comment by tom-englert** [comment]
The .wax file has absolutely nothing to do with your installation, its just a snapshots of the options that you have selected in the Wax editor.

**Comment by tom-englert** [comment]
@DarwinOL maybe you are mixing up the project references in the WiX project with the information in the .wax file?

You can always add a project reference to the WiX project manually, this is not related to the Wax editor, this is a WiX feature.

**Comment by tom-englert** [comment]
But why do you think you would need these entries in the .wax file? They have no meaning for WiX
