### ISSUE TITLE
Incorrect Directory Mappings 

### ISSUE THREAD

**Issue by kgwood39** [tom-englert/Wax#74]
Beginner at all of this, I've read the readme and don't understand what is happening here.  The directory mappings are automatically being generated when I select any project in my solution and they can't be edited within the Wax editor.  These are definitely not where I want items to go.
![image](https://user-images.githubusercontent.com/7604273/128211302-3f5f8536-20e4-45f4-bdb0-b33adc76a1a8.png)

I need a directory named "Services" and want to put the output of several projects of the solution into it.  How is that accomplished with wax?

**Comment by tom-englert** [comment]
This is where your projects output the items to. Wax assumes that the build output is exactly there where it should be at runtime.
If you configure your projects to output item to "A" while the items are expected to be at "B" during runtime, Wax can't help you.
