### ISSUE TITLE
Visual Studio 2022 install fails - Microsoft.VisualStudio.Component.CoreEdit missing

### ISSUE THREAD

**Issue by wilhelmmedetz** [tom-englert/Wax#77]
Visual Studio 2022 installatiuon fails.
Eror message: Microsoft.VisualStudio.Component.CoreEdit missing

[dd_VSIXInstaller_20211129152053_7850.log](https://github.com/tom-englert/Wax/files/7618760/dd_VSIXInstaller_20211129152053_7850.log)

**Comment by DanielD** [comment]
Same error here.

**Comment by tom-englert** [comment]
Duplicate of #76
