### ISSUE TITLE
Wrong references locations and missing references.

### ISSUE THREAD

**Issue by Hitchnt** [tom-englert/Wax#78]
When using the Wix Setup Editor, if  project  A that refences Project B. It will include those other files to the list in the set up. 

![image](https://user-images.githubusercontent.com/56658191/157455827-f51642d2-d63c-4b86-8a4f-7355f7210f72.png)

![image](https://user-images.githubusercontent.com/56658191/157453732-bdb2e532-71aa-4b17-b67c-a96391916756.png)

I have a runtimeconfig.json that is present here  From Project B but it is being map to Project A, which is the wrong folder so I will get the error saying that it can not find it when trying to build.

![image](https://user-images.githubusercontent.com/56658191/157456255-145fa793-6503-40a2-97be-e4459fa3b707.png)

Also, I having missing references, that would need to be manually added, but my current solution houses 20+ projects that are all needed, and adding one by one is not really feasible.

**Comment by tom-englert** [comment]
If a references b, and the file is marked as content and copy local, it should be also available as output of a.

**Comment by tom-englert** [comment]
I have no idea what you mean by missing references

**Comment by Hitchnt** [comment]
As of now it is doing  C:/../ProjectA/runtimeconfig.json , instead of doing  C:/../ProjectB/runtimeconfig.json which where the files is located at.

**Comment by Hitchnt** [comment]
![image](https://user-images.githubusercontent.com/56658191/157536258-3d70dbe7-c265-4106-8ce4-48089f66c742.png)

As for the missing references, here is an example of what I am seeing. I have only 10 items that showing  in the editor, but there are total of 14 with in the bin folder of project.

**Comment by tom-englert** [comment]
I can see only black stripes

**Comment by tom-englert** [comment]
Please provide a sample project where this behavior can be reproduceed

**Comment by Hitchnt** [comment]
ok can do

**Comment by Hitchnt** [comment]
https://github.com/Hitchnt/WixDemo

Here is a sample project on my machine I have a total of 40+ items in the editor picked up vs the 130+ in the editor

**Comment by tom-englert** [comment]
There is some invalid define in the `Product.wxs`: `<?define Project2_TargetDir=$(var.Project2.TargetDir)?>`
When I remove it, everything works fine.

**Comment by Hitchnt** [comment]
![image](https://user-images.githubusercontent.com/56658191/158588249-76d564c6-5fd7-41c5-a028-60b4d7409c50.png)


 I took out all 2  "define"  and reran the editor , but as seen in the picture there more then half of the item missing. I could be looking at this wrong or something else. I updated the repo to only have one define which was  generated by the editor ,

**Comment by tom-englert** [comment]
Now I see what you mean, Wax is designed to add only the files marked as "CopyLocal" - which in the new projects are only the files directly referenced in code, not the transitive dependencies - so the concept of this tool does no longer apply to projects that don't target NetFramework.

To get everything I would recommend to use the Heat utility that comes with WiX.

**Comment by Hitchnt** [comment]
Ah ok  I understand now, thank You very much
