### ISSUE TITLE
Installing Wax to Visual Studio 2022 version 17.2.1 completely crashes Visual Studio

### ISSUE THREAD

**Issue by WalterPiechulla** [tom-englert/Wax#79]
VS2022 compains about "MEF Service Broker Package" not being loaded correctly. VS2022 won't start anymore. Not even without loading any solution.

**Comment by tom-englert** [comment]
"MEF Service Broker Package" is part of VS, not of Wax, so this is a VS issue.

**Comment by WalterPiechulla** [comment]
It was indeed a VS problem and MS fixed it.


Please note! In the course of the introduction of new digitalization our domain and email addresses have been changed.

[https://octagon-company.com/cms/signature/Walter.png]<https://octagon-company.com/>


Von: tom-englert ***@***.***>
Gesendet: Dienstag, 31. Januar 2023 14:10
An: tom-englert/Wax ***@***.***>
Cc: Walter Piechulla ***@***.***>; Author ***@***.***>
Betreff: Re: [tom-englert/Wax] Installing Wax to Visual Studio 2022 version 17.2.1 completely crashes Visual Studio (Issue #79)


"MEF Service Broker Package" is part of VS, not of Wax, so this is a VS issue.
