### ISSUE TITLE
How the extension pick files from a project?

### ISSUE THREAD

**Issue by montoner0** [tom-englert/Wax#80]
I tried to use the extension but can't understand how it does picking of files from a project to include.
Some files from bin folder are added and some are not, no matter if they are content or compiled.
It would be nice to have some general description of the rules.

**Comment by tom-englert** [comment]
https://github.com/tom-englert/Wax/blob/master/Wax.Model/VisualStudio/Project.cs#L183

**Comment by montoner0** [comment]
It would be really appreciated if you could describe this in plain words. Digging through an unknown source code is like a "reverse engineering" of author's original thoughts and therefore error prone.

Moreover, I believe the description will save a lot of time to other people who will try to use the extension.

**Comment by tom-englert** [comment]
https://docs.microsoft.com/en-us/dotnet/api/vslangproj.vsproject?view=visualstudiosdk-2022

**Comment by montoner0** [comment]
It seems that it would be easier to find another way with Wix. Have a nice day.

**Comment by tom-englert** [comment]
Yes, you better find a commercial tool.

**Comment by montoner0** [comment]
> Yes, you better find a commercial tool.

It seems you've completely missed the point. I'm Windows Installer developer with more than five years experience. So I know and use the "commercial tools" alot.  

Lack of ability to document your tools and answer _simple_ and _basic_ questions isn't an attribute of commercial or open source software but an attitude of its developers toward other people.

**Comment by tom-englert** [comment]
It picks the files that the vsproject class reports as build output - what additional documentation do you expect for this?

And open source means you can contribute if you think something is missing, but not demand commercial level free of charge.

**Comment by montoner0** [comment]
I expect at least communication with words and not links to arbitrary pieces of code. Your first sentence is a much better answer than your previous two because it gives your intentions and thoughts as a developer.

People who use open source tools aren't expected to be an experts in inner things of these tools. That's why they're asking questions. The questions _are_ the contribution since they're showing lack of information from a developer and the answers _help_ other people with the same questions. 

I'm not asking you to solve my issues but just to tell about how the tool is intended to work because until then I can't say what is the issue.
